apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-angular-app-deployment
spec:
  replicas: 2          # Maintains three identical pods for high availability
  selector:
    matchLabels:
      app: my-angular-app
  template:
    metadata:
      labels:
        app: my-angular-app # Must match the Service selector above
    spec:
      containers:
      - name: angular-app-container
        image: 938377377710.dkr.ecr.us-east-2.amazonaws.com/my-angular-app:6d5821ac
        ports:
        - containerPort: 80


